services:

  comptapilot:
    build: .
    container_name: comptapilot-v3-comptapilot
    command: gunicorn -w 2 -b 0.0.0.0:5000 app:app
    ports:
      - "5001:5000"
    restart: always
    environment:
      - FLASK_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=comptapilot
      - POSTGRES_USER=comptapilot
      - POSTGRES_PASSWORD=comptapilot
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: comptapilot
      POSTGRES_USER: comptapilot
      POSTGRES_PASSWORD: comptapilot
    ports:
      - "5433:5432"
